FROM node:14 as builder

WORKDIR /app/drun-server

COPY ./ ./
RUN npm install
RUN npx nx build drun-api-delivery


FROM node:14 as runner

WORKDIR /app/drun-api-delivery
COPY ./package*.json ./
COPY --from=builder /app/drun-server/dist/apps/drun-api-delivery/ .

RUN npm install --production

CMD [ "node", "main.js" ]
