version: "3"

services:
  orders-service:
    build:
      context: "./services/orders-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - database
      - rabbitmq
    ports:
      - 3001:3001
    volumes:
      - ./services/orders-service:/opt/app/services/orders-service
      - ./core:/opt/app/core
      - /opt/app/core/node_modules
      - /opt/app/services/orders-service/node_modules

  payment-service:
    build:
      context: "./services/payment-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./services/payment-service:/opt/app/services/payment-service
      - ./core:/opt/app/core
      - /opt/app/core/node_modules
      - /opt/app/services/payment-service/node_modules

  delivery-service:
    build:
      context: "./services/delivery-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - 3002:3002
    volumes:
      - ./services/delivery-service:/opt/app/services/delivery-service
      - ./core:/opt/app/core
      - /opt/app/core/node_modules
      - /opt/app/services/delivery-service/node_modules

  logger-service:
    build:
      context: "./services/logger-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - database
      - rabbitmq
    ports:
      - 3003:3003
    volumes:
      - ./services/logger-service:/opt/app/services/logger-service
      - ./core:/opt/app/core
      - /opt/app/core/node_modules
      - /opt/app/services/logger-service/node_modules

  users-service:
    build:
      context: "./services/users-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - database
      - rabbitmq
    ports:
      - 3004:3004
    volumes:
      - ./services/users-service:/opt/app/services/users-service
      - ./core:/opt/app/core
      - /opt/app/core/node_modules
      - /opt/app/services/users-service/node_modules

  database:
    image: postgres
    restart: "no"
    volumes:
      - ./data/database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management
    restart: "no"
    logging:
      driver: none
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx:stable
    restart: "no"
    volumes:
      - ./data/nginx/dev.conf:/etc/nginx/conf.d/dev.conf
    depends_on:
      - orders-service
      - delivery-service
      - logger-service
      - users-service
    ports:
      - 80:80
      - 443:443
