version: "3"

services:
  user:
    build:
      context: .
      args:
        - service_src=./services/user-service/src
        - service_test=./services/user-service/test
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./services/user-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  order:
    build:
      context: .
      args:
        - service_src=./services/order-service/src
        - service_test=./services/order-service/test
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./services/order-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  delivery:
    build:
      context: .
      args:
        - service_src=./services/delivery-service/src
        - service_test=./services/delivery-service/test
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./services/delivery-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  payment:
    build:
      context: .
      args:
        - service_src=./services/payment-service/src
        - service_test=./services/payment-service/test
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./services/payment-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached
  
  discord:
    build:
      context: .
      args:
        - service_src=./services/discord-service/src
        - service_test=./services/discord-service/test
    command: bash -c "npm run start:dev"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./services/discord-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:management"
    logging:
      driver: none
    ports:
      - "5672:5672"
      - "15672:15672"
