version: "3"

services:
  order-service:
    build:
      context: "./services/orders-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - orders-service-database
      - rabbitmq
    ports:
      - 3001:3001
    volumes:
      - ./services/orders-service:/opt/app

  orders-service-database:
    image: postgres
    restart: "no"
    logging:
      driver: none
    ports:
      - 3101:5432
    env_file:
      - .env

  payment-service:
    build:
      context: "./services/payment-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./services/payment-service:/opt/app

  delivery-service:
    build:
      context: "./services/delivery-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - 3002:3002
    volumes:
      - ./services/delivery-service:/opt/app

  logger-service:
    build:
      context: "./services/delivery-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - logger-service-database
      - rabbitmq
    ports:
      - 3003:3003
    volumes:
      - ./services/logger-service:/opt/app
  
  logger-service-database:
    image: postgres
    restart: "no"
    logging:
      driver: none
    ports:
      - 3103:5432
    env_file:
      - .env

  users-service:
    build:
      context: "./services/users-service"
    restart: "no"
    env_file:
      - .env
    depends_on:
      - users-service-database
      - rabbitmq
    ports:
      - 3004:3004
    volumes:
      - ./services/users-service:/opt/app

  users-service-database:
    image: postgres
    restart: "no"
    logging:
      driver: none
    ports:
      - 3104:5432
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management
    restart: "no"
    logging:
      driver: none
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./data/nginx/prod.conf:/etc/nginx/conf.d/prod.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - order-service
      - delivery-service
      - logger-service
      - users-service
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
