version: "3"

services:
  authentication:
    build:
      context: .
      args:
        - service_src=./services/authentication-service/src
        - service_test=./services/authentication-service/test
    command: bash -c "npm run test; npm run start:dev"
    restart: on-failure
    env_file:
      - ./services/authentication-service/.env
    volumes:
      - ./services/authentication-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  order:
    build:
      context: .
      args:
        - service_src=./services/order-service/src
        - service_test=./services/order-service/test
    command: bash -c "npm run test; npm run start:dev"
    restart: on-failure
    env_file:
      - ./services/order-service/.env
    volumes:
      - ./services/order-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  delivery:
    build:
      context: .
      args:
        - service_src=./services/delivery-service/src
        - service_test=./services/delivery-service/test
    command: bash -c "npm run test; npm run start:dev"
    restart: on-failure
    env_file:
      - ./services/delivery-service/.env
    volumes:
      - ./services/delivery-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  payment:
    build:
      context: .
      args:
        - service_src=./services/payment-service/src
        - service_test=./services/payment-service/test
    command: bash -c "npm run test; npm run start:dev"
    restart: on-failure
    env_file:
      - ./services/payment-service/.env
    volumes:
      - ./services/payment-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached
  
  discord:
    build:
      context: .
      args:
        - service_src=./services/discord-service/src
        - service_test=./services/discord-service/test
    command: bash -c "npm run test; npm run start:dev"
    restart: on-failure
    env_file:
      - ./services/discord-service/.env
    volumes:
      - ./services/discord-service/src:/usr/src/app/service/src:cached
      - ./core:/usr/src/app/core:cached

  mongo:
    image: "mongo:latest"
    logging:
      driver: none
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:management"
    logging:
      driver: none
    ports:
      - "5672:5672"
      - "15672:15672"
